# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: ClusterIP
# could change type to LoadBalancer on a cloud provider
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
